twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        supported_locales:  "%supported_locales%"
        locale_names:  "%locale_names%"

when@test:
    twig:
        strict_variables: true
